apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecommerce-app-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecommerce-app-binding
subjects:
  - kind: ServiceAccount
    name: ecommerce-app-sa
roleRef:
  kind: Role
  name: ecommerce-app-role
  apiGroup: rbac.authorization.k8s.io