apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: us-central1-docker.pkg.dev/ecommerce-platform-dev-501414/ecommerce-images/product-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-service-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://34.121.17.43:5432/productdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "appuser"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20