apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: us-central1-docker.pkg.dev/ecommerce-platform-dev-501414/ecommerce-images/notification-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notification-service-config
          env:
            - name: GCP_PROJECT_ID
              value: "ecommerce-platform-dev-501414"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
